# Generated by Django 5.1.1 on 2024-11-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('ATTENDING', 'Attending'), ('NOT_ATTENDING', 'Not Attending'), ('IN_PROGRESS', 'In Progress')], default='IN_PROGRESS', max_length=20),
        ),
    ]
